# Generated by Django 5.0.6 on 2024-05-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blogpost_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
